### ISSUE TITLE
E185: Cannot find color scheme 'molokai' before install

### ISSUE THREAD

**Issue by avelino** [avelino/vim-bootstrap#107]
Error detected while processing /home/avelino/.vimrc:
    line  158:
    E185: Cannot find color scheme 'molokai'
    Press ENTER or type command to continue

**Comment by lacek** [comment]
Still see the same problem with vimrc generated with the merge: http://pastebin.com/pkF3FjYa
I am on Ubuntu 14.0.4 with vim 7.4.52 and installed [prerequisites](https://github.com/avelino/vim-bootstrap#linux)

**Comment by cassiobotaro** [comment]
Already fixed.

**Comment by ekajogja** [comment]
Still got this exact problem on Debian 8.5.0

**Comment by cassiobotaro** [comment]
@ekajogja What terminal are you using?

**Comment by ekajogja** [comment]
LXTerminal. Yes, dependencies are installed.

**Comment by cassiobotaro** [comment]
Change the line 170 to before the line 165. Can you test this?

**Comment by ekajogja** [comment]
Sorry, can you please write down the line?
Line 165 on my .vimrc is `if has ("gui_running")`
Do you mean line 170 is `set showcmd`

**Comment by cassiobotaro** [comment]
Put These lines:
```
if !exists('g:not_finish_vimplug')
  colorscheme molokai
endif
```
after
```
if &term =~ '256color'
  set t_ut=
endif
```

**Comment by ekajogja** [comment]
Done. Still unfixed.
![vimrc](https://cloud.githubusercontent.com/assets/3442811/17270543/085eb160-568f-11e6-8668-05363327930c.png)

**Comment by cassiobotaro** [comment]
@ekajogja What are your selected languages?

**Comment by ekajogja** [comment]
PHP, Go, HTML, JS.

**Comment by cassiobotaro** [comment]
Thanks, I download debian and will test here.

**Comment by cassiobotaro** [comment]
I could not replicate the problem.
![captura de tela_2016-07-30_15-24-05](https://cloud.githubusercontent.com/assets/3127847/17272324/d6976bc4-5669-11e6-8c24-2ddd14b30211.png)

**Comment by ekajogja** [comment]
Well, I guess I'll just comment out the colorscheme and move on 👌

**Comment by cassiobotaro** [comment]
@ekajogja It's weird and i am really curious about that. Let's try one more thing, open your vim and type `:colorscheme`. What's happened? After try to do `PlugInstall`. What's happened?

**Comment by ekajogja** [comment]
So I reinstalled vim and downloaded new vimrc. It works fine! 👍 
![vim-bootstrap-on-debian8-lxde](https://cloud.githubusercontent.com/assets/3442811/17281270/8d7ed0c8-57c5-11e6-965d-9c5131339397.png)

**Comment by cassiobotaro** [comment]
:tada: Nice! :tada: Good to know that debian is working well!

**Comment by SebastianKrieger** [comment]
got same error E185 on default linux ec2

**Comment by RobbiNespu** [comment]
I got same problem too after setup
```
$ sudo -E vim /etc/resolv.conf
[sudo] password for rnm: 
Error detected while processing /home/rnm/.vimrc:
line    3:
E185: Cannot find color scheme 'molokai'
Press ENTER or type command to continue
```
But then I realize, I have 2 vim folder and mistakenly use older one
```
 $ ls -l /usr/share/vim/
total 12
drwxr-xr-x.  3 root root 4096 May 23 13:35 vim80
drwxr-xr-x. 17 root root 4096 May 23 13:33 vim81
drwxr-xr-x. 17 root root 4096 May 23 13:33 vimfiles
```
Just move the scheme to new vim folder and worked fine
```
$ sudo mv /usr/share/vim/vim80/colors/molokai.vim /usr/share/vim/vim81/colors/
```

**Comment by hantmac** [comment]
mac os still has this problem.

**Comment by OrgYEET** [comment]
QUICK FIX to all such problems relating to theme installs.

open vimrc in vim `:e $MYVIMRC` 
then carefully type in plug command for the respective theme. for example in molokai theme
`Plug 'tomasr/molokai` where tomasr is the creator of the git repo where you downloaded the theme from.

then finally run `:PlugInstall` a couple of times just to be sure.
the save and close vim and restart it.
it should not show up again

**Comment by roostinghawk** [comment]
For mac, you could fix this problem by copying the colors folder from the following source to local "~/vim/"
https://github.com/tomasr/molokai

**Comment by avelino** [comment]
> For mac, you could fix this problem by copying the colors folder from the following source to local "~/vim/"

@roostinghawk does this problem persist or did you make a comment with guidelines in case the problem exists?

If the problem exists we have to solve it in vim-bootstrap not have a command line alternative

**Comment by alefhsousa** [comment]
@avelino maybe this problem persists for Mac users. I followed the documentation, but when I tried to open vim, I received this message:

<img width="941" alt="image" src="https://github.com/editor-bootstrap/vim-bootstrap/assets/9020828/3d8d07c5-f534-421f-93a7-6aab98b474c1">

I solved this by copying the colors folder from the Molokai repository and put into `~/.vim`

**Comment by avelino** [comment]
@alefhsousa share vimfile here

**Comment by maelfosso** [comment]
In 2024
```
❯ vim
Installing Vim-Plug...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84223  100 84223    0     0  25357      0  0:00:03  0:00:03 --:--:-- 25429
Error detected while processing /Users/maelfosso/.vimrc:
line  168:
E185: Cannot find color scheme 'molokai'
Press ENTER or type command to continue
```

**Comment by avelino** [comment]
@maelfosso Can you send a PR with the fix?
