### ISSUE TITLE
Save time in Vim NOW with these five weird tricks

### ISSUE THREAD

**Issue by avelino** [avelino/vim-bootstrap#116]
noremap <c-j> <c-w>j
    noremap <c-k> <c-w>k
    noremap <c-l> <c-w>l
    noremap <c-h> <c-w>h

http://usevim.com/2015/02/20/vim-tricks/
more: http://blog.unixphilosopher.com/2015/02/five-weird-vim-tricks.html

**Comment by hmleal** [comment]
+1

**Comment by adimircolen** [comment]
+1
