### ISSUE TITLE
Session Management with Vim

### ISSUE THREAD

**Issue by di3goleite** [avelino/vim-bootstrap#117]
Hello. What do you think about include an Session Management on vim-bootstrap project?
How it works: http://youtu.be/9vSER0O0asc

**Comment by lerrua** [comment]
@di3goleite i've used some sessions manager like vim-session for some weeks but stopped. I will try again, thanks for open issue.

**Comment by di3goleite** [comment]
@lerrua I'm using Vim session management, and this feature is so useful when a restart my laptop.
This plugin works very well.

**Comment by lerrua** [comment]
@di3goleite nice. :beer:
