### ISSUE TITLE
[Feature] Run vim-bootstrap in command line

### ISSUE THREAD

**Issue by camponez** [avelino/vim-bootstrap#118]
Is it possible to generate a new .vimrc using vim-bootstrap in a command line? Every time I make a pull from github I would like to generate a new .vimrc to replace the old one without going to the vim-bootstrap website.

**Comment by hmleal** [comment]
It is not necessary command line. Is there a plugin in Vim to make this update as the documentation:
https://github.com/avelino/vim-bootstrap#updating-to-the-latest-version

Just run inside of vim:
:VimBootstrapUpdate

**Comment by camponez** [comment]
But it updates from the website. It's not get the changes on the master branch as I would expect.

**Comment by hmleal** [comment]
But the site is synchronized with the master branch there is no difference.

**Comment by camponez** [comment]
@hmleal Some is not working then cause I have not got this cd181933b6b98bd8602bebc11dafb636c270d291 after update

**Comment by hmleal** [comment]
You're right, the site is not synchronized with the master branch. Now, we expect a response from @avelino or @lerrua

**Comment by avelino** [comment]
Sorry, I just do the deploy.
I'm going to open an issue to automate the deployment process.

**Comment by camponez** [comment]
I will maintain the branch from the PR #127 if anyone interested
