### ISSUE TITLE
Duplicated <leader>e map

### ISSUE THREAD

**Issue by hmleal** [avelino/vim-bootstrap#120]
1 - https://github.com/avelino/vim-bootstrap/blob/master/vim_template/vimrc#L313
2 - https://github.com/avelino/vim-bootstrap/blob/master/vim_template/vimrc#L326

And the second occurrence is wrong:

**BAD:**
let g:ctrlp_map = ',e'

**GOOD:**
let g:ctrlp_map = '\<leader>e'

**Comment by avelino** [comment]
you send PR?

**Comment by hmleal** [comment]
not yet

**Comment by hmleal** [comment]
which the correct mapping?

**Comment by avelino** [comment]
`let g:ctrlp_map = '<leader>e'`
