### ISSUE TITLE
vimshell does not work with vim < 703

### ISSUE THREAD

**Issue by LISTERINE** [avelino/vim-bootstrap#124]
It may be helpful to those with older versions of vim if the neobundle call for vimshell were to be wrapped in an if that checks the vim version before trying to install it to avoid the error.

**Comment by lerrua** [comment]
@LISTERINE  I believe many things on vim-bootstrap doesn't work on vim < 703

In README file is written:

### Pre-requisites
The distribution is designed to work with Vim >= 7.3.

**Comment by LISTERINE** [comment]
Well, how about that?
My apologies, just a little too eager to contribute.

**Comment by lerrua** [comment]
@LISTERINE it's fine. We can help with it. Do u use 7.2, right? Just find problem using vim-shell or another problem?

**Comment by lerrua** [comment]
@LISTERINE i'll accept your pull request. Please report another incompatibility with vim 7.2 if you see.
