### ISSUE TITLE
Consider to use vim-plug instead neobundle

### ISSUE THREAD

**Issue by alexandre** [avelino/vim-bootstrap#133]
Looks more stable, simpler and with async resources. Fair enough?

https://github.com/junegunn/vim-plug

(cc/ @avelino )

[ ]'s (hugs)

**Comment by lerrua** [comment]
@alexandre is fair enough to replace this?
```
NeoBundle 'Shougo/vimproc.vim', {
\ 'build' : {
\     'windows' : 'tools\\update-dll-mingw',
\     'cygwin' : 'make -f make_cygwin.mak',
\     'mac' : 'make -f make_mac.mak',
\     'linux' : 'make',
\     'unix' : 'gmake',
\    },
\ }
```

**Comment by alexandre** [comment]
@lerrua in this case not. I just think NeoBundle a little bit "unstable"....using this example + vim-plug, we would need a function to each build option.

**Comment by lerrua** [comment]
@alexandre maybe we can write this function for replace this config and migrate to vim-plug

**Comment by avelino** [comment]
@lerrua has many people talking well vim-plug, I think we can reconsider.
https://www.reddit.com/r/vim/comments/2gap6l/vimplug_a_minimalist_vim_plugin_manager/

**Comment by avelino** [comment]
@lerrua what do you think of giving the alternative user select which package control he will use via interface?

**Comment by gutierri** [comment]
:up:

**Comment by danofsatx** [comment]
It's time to move from neobundle. Shougo has [stopped development](https://www.reddit.com/r/vim/comments/47qbv9/neobundle_on_hiatus_or_done/d0fcdel) on it and moved to [dein.vim](https://github.com/Shougo/dein.vim)

**Comment by lerrua** [comment]
what do you guys think? Dein.vim or vim-plug?

**Comment by cassiobotaro** [comment]
I'm using vim-plug and it is really awesome. Dein looks imature.

**Comment by avelino** [comment]
vim-plug +1

**Comment by di3goleite** [comment]
vim-plug :+1:

**Comment by cassiobotaro** [comment]
I working on it, see #189 . We  have 2 unsolved problems that block this change.

**Comment by avelino** [comment]
fixed?

**Comment by cassiobotaro** [comment]
Yes!
