### ISSUE TITLE
Number of line on clipboard

### ISSUE THREAD

**Issue by adimircolen** [avelino/vim-bootstrap#134]
I do not know if you guys have noticed this by using MacVim.
After copying a line (using yy), mvim put on the clipboard the number of copied line?

**Comment by cassiobotaro** [comment]
@adimircolen what you think about this solution? http://stackoverflow.com/questions/5728259/how-to-clear-the-line-number-in-vim-when-copying

**Comment by cassiobotaro** [comment]
@lerrua Can you check this?

**Comment by cassiobotaro** [comment]
Probably already fixed
