### ISSUE TITLE
ruby.sh not exist!

### ISSUE THREAD

**Issue by adimircolen** [avelino/vim-bootstrap#135]
https://github.com/avelino/vim-bootstrap/commit/5a97f12dd37d2236ae8c1def0f26df032b50b599#diff-f0ca62ed1d606eceb1155462c8476412R23
this generate, 
`
silent !\curl -sSL https://raw.githubusercontent.com/avelino/vim-bootstrap/master/vim_template/langs/ruby/ruby.sh | bash -s stable
`
but ruby.sh not exist!
what must have here?

**Comment by avelino** [comment]
This is a bug, you need to check if the file exists before writing the line.
