### ISSUE TITLE
Run shell script command loop is generating empty lines 

### ISSUE THREAD

**Issue by lerrua** [avelino/vim-bootstrap#147]
![screen shot 2015-08-13 at 9 46 50 am](https://cloud.githubusercontent.com/assets/154603/9250069/a7ed32a6-41a0-11e5-8f66-4db94809e8f3.png)

**Comment by avelino** [comment]
If not exit `language.sh` not append on `silent` in vimrc file.

**Comment by lerrua** [comment]
os just do a `for` with valid bundles to generate vimrc. I'll do this later.

**Comment by avelino** [comment]
thanks!
