### ISSUE TITLE
Error 500 on http://vim-bootstrap.com/generate.vim

### ISSUE THREAD

**Issue by LadyDascalie** [avelino/vim-bootstrap#149]
Every time I try to generate a .vimrc (or .nvimrc), the same error 500 happens:

![screenshot 2015-08-20 16 35 56](https://cloud.githubusercontent.com/assets/3737347/9385980/a5a644e2-4759-11e5-83cd-058e9c49dab3.png)

Various combinations seem to cause this error. In my case eve selecting only Javascript for either Vim or NeoVim caused the error.

**Comment by avelino** [comment]
Must be intermitencia of `Google AppEngine`, we are planning to remove vim-bootstrap.

**Comment by LadyDascalie** [comment]
Well, thankfully, and as future reference, downloading an empty `.vimrc` or `.nvimrc` and modifying it to add in the languages manually works fine.

Thank you for for taking the time to answer, it seems to be running fine now!
