### ISSUE TITLE
Append vim-scripts/php_getset.vim

### ISSUE THREAD

**Issue by lockland** [avelino/vim-bootstrap#151]
I think would be very interest to include php getter and setters generator when user choose php language

NeoBundle 'vim-scripts/php_getset.vim'

**Comment by cassiobotaro** [comment]
Generate getters and setters can be a bad thing in wrong hands. You can destroy the encapsulation of your objects. 
A tip is, if you want to use, add this line in your .vimrc.local.bundle : 
`Plug 'vim-scripts/php_getset.vim'`

**Comment by lockland** [comment]
Uhuummm !!! kkkk

Tks for your reply
