### ISSUE TITLE
The :VimBootstrapUpdate command fails.

### ISSUE THREAD

**Issue by josernestodavila** [avelino/vim-bootstrap#152]
After upgrading to the current version of vim-bootstrap, I get the following error message when I launch vim:

```
Error detected while processing /home/jdavila/.vim/bundle/vim-bootstrap-updater/plugin/vim_bootstrap_updater.vim:
line   4:
E836: This Vim cannot execute :python after using :py3
E263: Sorry, this command is disabled, the Python library could not be loaded.
```

I'm using **Vim 7.4.827** and also have installed both **Python 2.7.10** and **Python 3.4.2**.

**Comment by gbrennon** [comment]
Hey @josernestodavila which OS are you using?

It seems like your VIM isn't supporting python2, only python3!

@lerrua lets create an issue on your plugin github ;)

I was porting the plugin to python3 but I got a messed up .vimrc :(

**Comment by gambledor** [comment]
+ 1

**Comment by josernestodavila** [comment]
@gbrennon I see this issue at work, where we use Fedora (I have F22 in my workstation). There is a workaround to this issue in https://github.com/avelino/vim-bootstrap/issues/156

**Comment by lerrua** [comment]
it's fixed now 👍
