### ISSUE TITLE
inserting letter q instead space in terminal

### ISSUE THREAD

**Issue by rafaelcapucho** [avelino/vim-bootstrap#155]
Hello,

Opening simple files (or creating ones, any case), like that: `vim hello.py` when I chance to `ÌNSERT MODE` appears one 'q' letter in the bottom:

![screen8](https://cloud.githubusercontent.com/assets/163367/10698676/fc76dec6-7990-11e5-9a30-5ecf3ba6e356.png)

And when I press the space bar that letter is inserted instead of a space (everytime):

![screen9](https://cloud.githubusercontent.com/assets/163367/10698714/380fba5c-7991-11e5-8e07-bfabae8b3e92.png)

When I press `Enter` to a new like, it disappear:

![screen10](https://cloud.githubusercontent.com/assets/163367/10698737/5afb6836-7991-11e5-88d5-13015184cdd3.png)

I'm using a fresh vim-bootstrap install, I already tried to reinstall, using kubuntu.

In gvim it is working ok.

Thank you!

Vim Version 7.4

**Comment by cassiobotaro** [comment]
@rafaelcapucho Can you test this again with a new version of vim-bootstrap?

**Comment by cassiobotaro** [comment]
@rafaelcapucho any news about this issue?

**Comment by cassiobotaro** [comment]
I have the same problem in a previous ubuntu version, but is already fixed. If someone have that problem, feel free to reopen this issue.
