### ISSUE TITLE
vim_bootstrap_updater.vim - 'cannot execute :python after using :py3'

### ISSUE THREAD

**Issue by kendricktan** [avelino/vim-bootstrap#156]
This is my first time reporting a bug, so please excuse any protocols that I've breached.

System: Fedora 22 LXDE, with python2, python2-devel, python3, python3-devel installed.

Anyhow, upon starting up with the pre configured vimrc it'll pop out the annoying message:

    E836: This Vim cannot execute :python after using :py3
    E263: Sorry, this command is disabled, the Python library could not be loaded.
    line    5:
    E836: This Vim cannot execute :python after using :py3
    E263: Sorry, this command is disabled, the Python library could not be loaded.
    line    6:
    E836: This Vim cannot execute :python after using :py3
    E263: Sorry, this command is disabled, the Python library could not be loaded.

Quick fix done via changing ~/.vim/bundle/vim-bootstrap-updater/plugin/vim_bootstrap_updater.vim

    python import sys                                                        
    python import vim                                                        
    python sys.path.append(vim.eval('expand("<sfile>:h")')) 

to

    python3 import sys
    python3 import vim
    python3 sys.path.append(vim.eval('expand("<sfile>:h")'))

**Comment by asfelix** [comment]
This solution work for me. Thank's!

**Comment by cassiobotaro** [comment]
This solution works for me too. thanks @kendricktan

**Comment by uggla** [comment]
The above solution from @kendricktan just remove the vim errors at startup.
But you will still face some errors if you try to enter `:VimBootstrapUpdate` into vim.

So this short patch file to allow VimBootstrapUpdate to work with python3 (Fedora 22).
[VimBootstrapUpdate.patch.zip](https://github.com/avelino/vim-bootstrap/files/99019/VimBootstrapUpdate.patch.zip)

**Comment by cassiobotaro** [comment]
This became a problem on ubuntu 16.04 LTS too, because now, python3 is default in vim.

**Comment by rahulunair** [comment]
Is there a fix for this?, on ubuntu 14.04, changing python to python3 in vim_bootstrap_updater.vim does not fix the issue.

**Comment by cassiobotaro** [comment]
@rahulunair but ubuntu 14.04 has python as default.

**Comment by mswell** [comment]
This solution works to me on Ubuntu 16.04. Thx :)

**Comment by ffabiorj** [comment]
Someone has a solution for the problem?
I try use the command :VimBootstrapUpdate and happens this below

Error detected while processing function VimBootstrapUpdate:
line   23:
E836: This Vim cannot execute :python after using :py3
E263: Sorry, this command is disabled, the Python library could not be loaded.

**Comment by afdallah** [comment]
This solution work for me. I'm running Ubuntu 16.04 anw. Thanks :)

**Comment by relson** [comment]
I used the neovim and works great after install the python support to neovim `pip2 install neovim` I guess needs only update the documentation

**Comment by cassiobotaro** [comment]
@lerrua You can close this issue.
