### ISSUE TITLE
Create a pypi package to use vim-boostrap CLI

### ISSUE THREAD

**Issue by lerrua** [avelino/vim-bootstrap#159]
We can continue the #145 PR writing a module to use the generate as 

```
pip install vim-bootstrap
vimbootstrap --langs=python,ruby,js
```

And get the vimrc file instantly

**Comment by avelino** [comment]
+1

**Comment by vmesel** [comment]
Another awesome thing is to already update the .vimrc file and make a backup of it, so the program, if errors are printed, roll back to the last version!

**Comment by avelino** [comment]
Done when we migrate to Go
