### ISSUE TITLE
create docker environment for vim-bootstrap.com

### ISSUE THREAD

**Issue by avelino** [avelino/vim-bootstrap#167]
- [x] dockerfile (run Go + Glide in new branch https://github.com/avelino/vim-bootstrap/tree/golang)
- [x] docker-compose

**Comment by lerrua** [comment]
:+1:

**Comment by sfrique** [comment]
I might take a look into this.

**Comment by avelino** [comment]
@sfrique update issue, new version migrate to Go + Glide (package manage)

**Comment by sfrique** [comment]
so i should use this branch instead of master correct?

I had the docker kind of working, but I also had installed youcomplete me, is there any reason why this plugin is not been used?

I am not sure if I should commit the Dockerfile using youcomplete me as it isn't a part of vim-bootstrap.
