### ISSUE TITLE
Open github file/line (website) error

### ISSUE THREAD

**Issue by cassiobotaro** [avelino/vim-bootstrap#170]
Requires additional config to work. Look at [here](http://felixge.de/2013/08/08/vim-trick-open-current-line-on-github.html), but git url was returning wrong url.

Tried in vim 7.4 and git 1.9.1 and xfce environment

**Comment by cassiobotaro** [comment]
Solution in vim 7.4.712, git 2.5.0 and xfce environment:

https://github.com/avelino/vim-bootstrap/blob/master/vim_template/vimrc#L423
```diff
- noremap ,o :!echo `git url`/blob/`git rev-parse --abbrev-ref HEAD`/%\#L<C-R>=line('.')<CR> \| xargs open<CR><CR>
+ noremap ,o :!echo `git url`/blob/`git rev-parse --abbrev-ref HEAD`/%\#L<C-R>=line('.')<CR> \| xargs xdg-open<CR><CR>
```

**Comment by avelino** [comment]
+1

**Comment by WilsonChiang** [comment]
+1 thanks

**Comment by avelino** [comment]
@cassiobotaro send PR pls

**Comment by cassiobotaro** [comment]
@avelino Yep. I wiil do it later.

**Comment by WilsonChiang** [comment]
Any idea what might cause a 'cannot find directory' error?

**Comment by cassiobotaro** [comment]
@WilsonChiang  what's your git version?

try this in .gitconfig:
`[alias]
	url =! bash -c 'git config --get remote.origin.url | sed -E "s/\\\\.git//g"'`

**Comment by WilsonChiang** [comment]
Sorry it seems to actually be a `/blob//path/to/my/file` does not exist error. I think it doesn't know what blob is.

**Comment by cassiobotaro** [comment]
@WilsonChiang Maybe #188 can help you.
