### ISSUE TITLE
Bootstrap is not aware of Neovim’s XDG base directory specification support

### ISSUE THREAD

**Issue by ZyX-I** [avelino/vim-bootstrap#172]
Generated file puts bundles to ~/.nvim/bundle, but ~/.nvim is no longer used by default. Bundles would be expected in `${XDG_DATA_HOME:-$HOME/.local/share}/nvim/bundle` (`${XDG_CONFIG_HOME:-$HOME/.config}/nvim/bundle` is a wrong place because bundles are not a configuration and thus this is not XDG compliant). Also downloaded file should be named `init.vim` and not `nvimrc`.

**Comment by avelino** [comment]
@ZyX-I You can send a pull request with this fix?

**Comment by gutierri** [comment]
I tested and is working as expected **neovim**.

The editors.py file to point to the right place -> https://github.com/avelino/vim-bootstrap/blob/master/editors.py#L33

**Comment by gutierri** [comment]
Close?
