### ISSUE TITLE
Accept URL parameters 

### ISSUE THREAD

**Issue by marioy47** [avelino/vim-bootstrap#174]
Hello,

I'm not proficient in Python, so by looking at the code I'm not sure if this is already supported. But it would be great if I could do something like:

```bash
curl http://vim-bootstrap.com/generate?editor=vim&langs=javascript,php,html,ruby > ~/.vimrc
```

**Comment by avelino** [comment]
working:

    curl 'http://vim-bootstrap.com/generate.vim' --data 'langs=javascript&langs=php&langs=html&langs=ruby&editor=vim'

**Comment by marioy47** [comment]
:+1:
