### ISSUE TITLE
Could not resolve airline theme

### ISSUE THREAD

**Issue by pedroteixeirarj** [avelino/vim-bootstrap#175]
Hi,

I've recently installed Vim-Bootstrap and when I load Vim I receive the following message:
"Could not resolve airline theme "powerlineish". Themes have been migrated to github.com/vim-airline/vim-airline-themes."

Thank you.

**Comment by lerrua** [comment]
@pedroteixeirarj the PR #173 fixed this issue.
I did the deploy today. :+1:
