### ISSUE TITLE
term option is not valid in Neovim

### ISSUE THREAD

**Issue by gutierri** [avelino/vim-bootstrap#178]
`set term` was removed in Neovim (see https://neovim.io/doc/user/options.html#%27term%27)
This option is present in the vimrc and init.vim (Neovim). In Neovim has an error at startup.

```
E518: Unknown option: term=gnome-256color
```

I think to solve this(**pull request**):

```
  {% if editor.name == "vim" %}
  if $COLORTERM == 'gnome-terminal'
    set term=gnome-256color
  else
    if $TERM == 'xterm'
      set term=xterm-256color
    endif
  endif
  {% endif %}
```

**Comment by lerrua** [comment]
@gutierri merged and deployed. You can test in production via website now.
