### ISSUE TITLE
Get an Error: 500 when selecting javascript as a language option on the website

### ISSUE THREAD

**Issue by ederoyd46** [avelino/vim-bootstrap#181]
Also occurs when running the curl command

curl --data "langs=javascript&editor=vim" http://vim-bootstrap.com/generate.vim

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://vim-bootstrap.com/generate.vim&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>

**Comment by drgarcia1986** [comment]
Works fine for me 
```
curl -X POST -d "langs=javascript&editor=vim" http://vim-bootstrap.com/generate.vim
```

**Comment by ederoyd46** [comment]
Yep, also works for me now.
