### ISSUE TITLE
Vimproc build fails on FreeBSD

### ISSUE THREAD

**Issue by tofagerl** [avelino/vim-bootstrap#183]
The fix is quite easy, just go to ~/.vim/bundle/vimproc.vim and run gmake, but of course it would be easier if the default bootstrap settings included this tiny tweak. 
I think it SHOULD just a matter of adding ```'freebsd' : 'gmake' ``` after windows, cygwin, mac and unix, but the only thing that works for me is to manually build it, so who knows what the proper solution is.

**Comment by cassiobotaro** [comment]
@tofagerl I testing a replace of neobundle with vim-proc, can you test in freebsd for me? https://github.com/cassiobotaro/vim-bootstrap/tree/vim_plug

**Comment by tofagerl** [comment]
Could you link me a generic .vimrc and I'll just overwrite my own and delete .vim for a test run? That would be a whole lot easier for me than learning how to host vim-bootstrap ;)

**Comment by cassiobotaro** [comment]
@tofagerl  Generic .vimrc to test https://gist.github.com/cassiobotaro/d013ed5ff032d9866924496ca3e75515

**Comment by tofagerl** [comment]
Oooh, pretty...
Oooh, fast!

Yeah, works fine. I am having some issues with vimrc.local.bundles not being installed, but that's all.

**Comment by cassiobotaro** [comment]
@tofagerl Test the new vim-bootstrap version deployed today. If it's ok, can you close this issue, please?

**Comment by tofagerl** [comment]
I don't have a BSD machine handy for testing. Might be a while.

**Comment by cassiobotaro** [comment]
@tofagerl any news about this issue? can we close?

**Comment by tofagerl** [comment]
Yes. Though I've only tested nvim.
