### ISSUE TITLE
set mouse=a

### ISSUE THREAD

**Issue by Icehunter** [avelino/vim-bootstrap#184]
I was just wondering if this is something that people use a lot?

I have it set in my .vimrc but when I the update scripts this is replaced and disappears. I use it to enable scroll wheel scrolling of the buffer instead of scrolling the history of the window.

Is there any way to keep that in the file during the update process?

Thanks!

Edit:
Specifically it get's replaced when I run: VimBootstrapUpdate

**Comment by cassiobotaro** [comment]
Set this in your local file `.vimrc.local` and avoid this replacement.

**Comment by Icehunter** [comment]
Ha! I did not know about that. Thanks!
