### ISSUE TITLE
Error when opening file

### ISSUE THREAD

**Issue by lucasmezencio** [avelino/vim-bootstrap#190]
A few days ago I realized that my Vim Bootstrap was outdated, so I tried to update it.
After the update, every time I open the Vim, the program displayed some errors. So, I tried to reinstall from zero.
After reinstalling, when I open Vim, no error is displayed.
**BUT**, when I open any file in Vim, some errors are displayed (in a very short seconds).

Some examples below.

Opening `.vimrc` file:
![screen shot 2016-05-11 at 17 35 12](https://cloud.githubusercontent.com/assets/472412/15195559/c80c97c8-179e-11e6-8fd4-803d13b3ee23.png)

Opening a `php` file:
![screen shot 2016-05-11 at 17 36 46](https://cloud.githubusercontent.com/assets/472412/15195619/f3cc8404-179e-11e6-81e5-e78e977c81f1.png)

**Comment by 9IPHP** [comment]
The same issue.

**Comment by lucasmezencio** [comment]
@9IPHP some weird thing happened here. The errors stopped to being shown after I did not do ANYTHING.
They just stopped to being shown.

Try to update/upgrade all packages that you have installed with Homebrew or even OSX.

I will close this issue for now. :)

**Comment by lucasmezencio** [comment]
Sorry about my english. :$
