### ISSUE TITLE
both cURL and the site are giving me a 500 Internal Server Error

### ISSUE THREAD

**Issue by stuartweir** [avelino/vim-bootstrap#192]
I believe it's fairly self explanatory, however I tried to download the .vim file for my selected langs, and it gave me an internal server error. cURL'ing just filled a `.vimrc` file with the contents of the error, that being of an Internal Server Error.

-Stu

**Comment by cassiobotaro** [comment]
What languages you select?

**Comment by stuartweir** [comment]
JS, Ruby, Haskell, Elixir, Python, C, Lua, Ocaml, Go, Erlang, php, html

`curl 'http://vim-bootstrap.com/generate.vim' --data 'langs=javascript&langs=ruby&langs=haskell&langs=elixir&langs=python&langs=c&langs=lua&langs=ocaml&langs=go&langs=erlang&langs=php&langs=html&editor=vim' > ~/.vimrc`

**Comment by cassiobotaro** [comment]
Maybe a network restriction. I test here and I don't have any problems.
