### ISSUE TITLE
init.vim: setting binary mode sets vim to use tabs instead of spaces (noexpandtab)

### ISSUE THREAD

**Issue by ahirschberg** [avelino/vim-bootstrap#193]
After the initial config is run, vim has `noexpandtab` enabled, because executing `set binary` sets this option. The `set expandtab` line in init.vim should be moved below `set binary` so that it gets executed after. See http://stackoverflow.com/questions/27770329/why-does-set-binary-reset-expandtab-property and/or http://vimdoc.sourceforge.net/htmldoc/options.html#'binary'

**Comment by cassiobotaro** [comment]
Fixed with 663f676
