### ISSUE TITLE
Vim airline arrows looks strange

### ISSUE THREAD

**Issue by PabloValor** [avelino/vim-bootstrap#196]
I just installed the .vimrc file and the arrows looks strange. I have already installed the powerline fonts, I'm using `Inconsolata-g for Powerline Medium 11`

![screenshot from 2016-07-04 21 29 54](https://cloud.githubusercontent.com/assets/6534833/16571274/20ff703e-422f-11e6-95f4-514796e662e0.png)

Any hint?

**Comment by cassiobotaro** [comment]
Added in your .vimrc.locals:
`let g:airline_powerline_fonts = 1`

**Comment by PabloValor** [comment]
@cassiobotaro Thanks!
