### ISSUE TITLE
Erro using nvim

### ISSUE THREAD

**Issue by adimircolen** [avelino/vim-bootstrap#202]
Error detected while processing /Users/adimircolen/.config/nvim/plugged/vim-bootstrap-updater/plugin/vim_bootstrap_updater.vi
m:
line   10:
E117: Unknown function: provider#python#Call
Press ENTER or type command to continue

**Comment by landrade** [comment]
+1

**Comment by cassiobotaro** [comment]
You have to install python client on neovim.

`pip install --user --upgrade neovim`

You can read about [here](https://neovim.io/doc/user/provider.html#provider-python).

I will update the README with this info asap. thank's to report.
