### ISSUE TITLE
gvim on windows

### ISSUE THREAD

**Issue by julianobarbosa** [avelino/vim-bootstrap#205]
Is possible I use vim-bootstrap on GVIM on windows ?

When I try install I Get This message:

Error detected while processing C:\Users\UserName\.vimrc:
line   25:
E117: Unknown function: plug#begin
line   30:
E492: Not an editor command: Plug 'scrooloose/nerdtree'
line   31:
E492: Not an editor command: Plug 'jistr/vim-nerdtree-tabs'
line   32:
E492: Not an editor command: Plug 'tpope/vim-commentary'
line   33:
E492: Not an editor command: Plug 'tpope/vim-fugitive'
line   34:
E492: Not an editor command: Plug 'ctrlpvim/ctrlp.vim'
line   35:
E492: Not an editor command: Plug 'vim-airline/vim-airline'
line   36:
E492: Not an editor command: Plug 'vim-airline/vim-airline-themes'
line   37:
E492: Not an editor command: Plug 'airblade/vim-gitgutter'
line   38:
E492: Not an editor command: Plug 'sheerun/vim-polyglot'
line   39:
E492: Not an editor command: Plug 'vim-scripts/grep.vim'
line   40:
E492: Not an editor command: Plug 'vim-scripts/CSApprox'
line   41:
E492: Not an editor command: Plug 'bronson/vim-trailing-whitespace'
line   42:
E492: Not an editor command: Plug 'Raimondi/delimitMate'
line   43:
E492: Not an editor command: Plug 'majutsushi/tagbar'
line   44:
E492: Not an editor command: Plug 'scrooloose/syntastic'
line   45:
E492: Not an editor command: Plug 'Yggdroot/indentLine'
line   46:
E492: Not an editor command: Plug 'avelino/vim-bootstrap-updater'
line   52:
E492: Not an editor command: Plug 'Shougo/vimproc.vim', {'do': g:make}
line   55:
E492: Not an editor command: Plug 'xolox/vim-misc'
line   56:
E492: Not an editor command: Plug 'xolox/vim-session'
line   59:
E492: Not an editor command:   Plug 'Shougo/vimshell.vim'
line   64:
E492: Not an editor command:   Plug 'SirVer/ultisnips'
line   68:
E492: Not an editor command: Plug 'honza/vim-snippets'
line   71:
E492: Not an editor command: Plug 'tomasr/molokai'
line   74:
E492: Not an editor command: Plug 'vim-scripts/c.vim'
line   77:
E492: Not an editor command: Plug 'davidhalter/jedi-vim'
line   80:
E492: Not an editor command: Plug 'vim-perl/vim-perl'
line   81:
E492: Not an editor command: Plug 'c9s/perlomni.vim'
line   84:
E492: Not an editor command: Plug 'amirh/HTML-AutoCloseTag'
line   85:
E492: Not an editor command: Plug 'hail2u/vim-css3-syntax'
line   86:
E492: Not an editor command: Plug 'gorodinskiy/vim-coloresque'
line   87:
E492: Not an editor command: Plug 'tpope/vim-haml'
line   88:
E492: Not an editor command: Plug 'mattn/emmet-vim'
line   91:
E492: Not an editor command: Plug 'arnaud-lb/vim-php-namespace'
line   93:
E492: Not an editor command: Plug 'tpope/vim-rails'
line   94:
E492: Not an editor command: Plug 'tpope/vim-rake'
line   95:
E492: Not an editor command: Plug 'tpope/vim-projectionist'
line   96:
E492: Not an editor command: Plug 'thoughtbot/vim-rspec'
line   97:
E492: Not an editor command: Plug 'ecomba/vim-ruby-refactoring'
line  104:
E117: Unknown function: plug#end

**Comment by off99555** [comment]
I have this issue too.

**Comment by cassiobotaro** [comment]
Try execute this commands before open vim.
```
md ~\vimfiles\autoload
$uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
(New-Object Net.WebClient).DownloadFile($uri, $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath("~\vimfiles\autoload\plug.vim"))
```

**Comment by cassiobotaro** [comment]
@julianobarbosa any news about this issue?

**Comment by julianobarbosa** [comment]
@cassiobotaro I remove windows S.O

**Comment by cassiobotaro** [comment]
@off99555 Still having this issue?

**Comment by off99555** [comment]
@cassiobotaro I don't use this anymore. I use Ultimate vimrc.
Sorry.

**Comment by cassiobotaro** [comment]
Closing this issue because unfortunately we don't have members with the same problem anymore. Maybe [https://github.com/avelino/vim-bootstrap/issues/205#issuecomment-258207058](https://github.com/avelino/vim-bootstrap/issues/205#issuecomment-258207058) can solve the problem.

**Comment by fxacc** [comment]
#205(comment) work on my win10
