### ISSUE TITLE
issue with using sudo vim/VimBootstrapUpdate

### ISSUE THREAD

**Issue by Icehunter** [avelino/vim-bootstrap#206]
Hi!

I've been using this package for quite some time and after the switch over from neobundle to what we have now I've been unable to use VimBootstrapUpdate as it clears out my .vimrc file.

I've also come across an issue (randomly on regular files) and 100% broken on the following command:

```
sudo vi /etc/hosts
```

The moment I start typing something in the buffer I get the following errors:

![image](https://cloud.githubusercontent.com/assets/677341/18573450/710240d4-7b78-11e6-9255-dffb1fff8359.png)

Here is my current .vimrc
[vimrc.txt](https://github.com/avelino/vim-bootstrap/files/475949/vimrc.txt)

I'm using macOS Sierra (but this was present in El Capitain as well). I'm also using Vim8 as follows:

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 17:28:17)
MacOS X (unix) version
Included patches: 1-2
Compiled by Homebrew

Is there any additional info I can provide for how to fix this?

**Comment by cassiobotaro** [comment]
@lerrua Can you take a look?

**Comment by cassiobotaro** [comment]
@Icehunter  After switch, you run `:PlugInstall` ?

**Comment by Icehunter** [comment]
@cassiobotaro Yup. I actually even deleted the vim folder itself to start from scratch.

**Comment by lerrua** [comment]
@Icehunter maybe can be a local vimrc config? I'm using mac here with vim8 (installed via homebrew) and I couldn't replicate this error.

**Comment by Icehunter** [comment]
I'm using homebrew as well; I do have a local file but after deleting it I'm still getting that issue.

https://github.com/Icehunter/environments/blob/master/.vimrc.local

You can see my setup/config for system here:
https://github.com/Icehunter/environments/blob/master/setup.sh

**Comment by lucasmezencio** [comment]
I am having the same issue. :(

**Comment by lerrua** [comment]
@Icehunter @lucasmezencio can you guys do a test for me? Try install macvim using `brew install macvim` and run it with `sudo mvim -v /etc/hosts` on terminal and let me know if it will works please.

**Comment by lucasmezencio** [comment]
@lerrua I have already installed MacVim, but just to override system Vim. I installed with the following:
`brew install macvim --HEAD --with-cscope --with-lua --with-override-system-vim --with-luajit --with-python`

I did not remember to have opened MacVim, neither with `mvim` (I not like MacVim, I do prefer command line Vim hahaha), so using `vim` I have experiencing this issue. :(

I am using Vim 8.

**Comment by lerrua** [comment]
@lucasmezencio yep, sure. I'm using vim on command line too, macvim works via GUI and command line also. The difference is using via `mvim -v file` will open just on terminal (you can do `alias vim=mvim -v` for example), but anyway with mvim command we called vim binary running with some mac preferences and the last version runs on vim 8. 
With macvim compiled I don't have this error.

**Comment by Icehunter** [comment]
Okay; so I think I found something weird...

This works just fine:
```
sudo vim /etc/hosts
```

I aliased "vi" in my zshrc file to be:
```
alias vi="vim"
```

Using sudo vi breaks it. I do "vi" since it's 1 character less...

**Comment by lucasmezencio** [comment]
@lerrua I forgot to do this test yesterday. I will try this tonight.
@Icehunter I will try this too. :smiley:

**Comment by lucasmezencio** [comment]
Oh, I detected that the error I am getting is another error.
```
Error detected while processing /Users/alucard/.vim/plugged/vim-bootstrap-updater/plugin/vim_bootstrap_updater.vim:
line   10:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
line   11:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
line   12:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
line   13:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
Press ENTER or type command to continue
```

And, when I try to type any character after `--INSERT--` method enabled, I am getting this error too:
```
Error detected while processing /Users/alucard/.vim/plugged/ultisnips/autoload/UltiSnips.vim:                                                                                                                      
line    7:                                                                                                                                                                                                         
E887: Sorry, this command is disabled, the Python's site module could not be loaded.                                                                                                                               
Press ENTER or type command to continue
```

I have tried all of your suggestions, @lerrua and @Icehunter.
😭

**Comment by lucasmezencio** [comment]
The problem is getting bigger, I guess. :~~
O did `brew unlink python && brew link --force python` then `brew uninstall macvim && brew install macvim` and the startup error has gone.
But, when I try to type anything after `--INSERT--` method enabled, I am getting this error now:
```
Error detected while processing /Users/alucard/.vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /Users/alucard/.vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /Users/alucard/.vim/plugged/ultisnips/autoload/UltiSnips.vim:
line    8:
ImportError: No module named UltiSnips
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
```

**Comment by lucasmezencio** [comment]
@avelino @lerrua any idea? 😢

**Comment by lerrua** [comment]
@lucasmezencio are you using El Capitain or Sierra?

**Comment by lucasmezencio** [comment]
Sorry guys.
I forgot to say that after I upgraded from El Capitan to Sierra, the bug disappeared.

But `neovim` was still with the same bug.
Talking with @cassiobotaro, he suggested me to run `sudo pip install neovim`, after that, the errors on `neovim` disappeared.

I think this issue can be closed. 😉

**Comment by avelino** [comment]
@lucasmezencio thanks feedback
