### ISSUE TITLE
Convert vim-bootstrap package to Go

### ISSUE THREAD

**Issue by avelino** [avelino/vim-bootstrap#208]
Improvements:
- binary distribute (command line)
- use less server resource

**Comment by hmleal** [comment]
👍

**Comment by drgarcia1986** [comment]
How can I help with this issue 😄  ?

**Comment by avelino** [comment]
This ready, this week I'm going to do the dockerfile and compose, put into production

**Comment by drgarcia1986** [comment]
Great 👏
