### ISSUE TITLE
Error detected while processing /Users/foo/.vimrc:

### ISSUE THREAD

**Issue by glaucocustodio** [avelino/vim-bootstrap#209]
I followed all the steps for macOS on README and if I try to open vim (not neo) or run `vim +PlugInstall +qall` I get a lot of errors:

```
Error detected while processing /Users/foo/.vimrc:
line   25:
E117: Unknown function: plug#begin
line   30:
E492: Not an editor command: Plug 'scrooloose/nerdtree'
line   31:
E492: Not an editor command: Plug 'jistr/vim-nerdtree-tabs'
line   32:
E492: Not an editor command: Plug 'tpope/vim-commentary'
line   33:
E492: Not an editor command: Plug 'tpope/vim-fugitive'
line   34:
E492: Not an editor command: Plug 'ctrlpvim/ctrlp.vim'
line   35:
E492: Not an editor command: Plug 'vim-airline/vim-airline'
line   36:
E492: Not an editor command: Plug 'vim-airline/vim-airline-themes'
line   37:
E492: Not an editor command: Plug 'airblade/vim-gitgutter'
line   38:
E492: Not an editor command: Plug 'sheerun/vim-polyglot'
line   39:
E492: Not an editor command: Plug 'vim-scripts/grep.vim'
line   40:
E492: Not an editor command: Plug 'vim-scripts/CSApprox'
line   41:
E492: Not an editor command: Plug 'bronson/vim-trailing-whitespace'
line   42:
E492: Not an editor command: Plug 'Raimondi/delimitMate'
```

Ps: I already have `git` and `ctags` installed.

**Comment by cassiobotaro** [comment]
Do you have this file at your home directory? ~/.vim/autoload/plug.vim

**Comment by glaucocustodio** [comment]
I do not even have the `~/.vim` directory, let alone the `~/.vim/autoload/`.

**Comment by cassiobotaro** [comment]
@glaucocustodio it's strange, @lerrua also uses macOS and it works. Can you share your generated .vimrc with us, @lerrua can replicate this issue.

**Comment by lerrua** [comment]
@glaucocustodio are you using El Capitain or Sierra?

**Comment by vmesel** [comment]
@cassiobotaro Is this a duplicated issue? #204

**Comment by cassiobotaro** [comment]
@vmesel maybe, but are different OS...

**Comment by cassiobotaro** [comment]
@glaucocustodio Related issues were resolved by reinstalling vim, apparently macos changes symbolic links when updated, replacing vim installed with homebrew with macos native vim.
If bug persists, feel free to reopen this issue or open a new one.
Thanks to report!

**Comment by beeblebrox3** [comment]
I have the same problem, but on linux.

I'm using a fresh install of elementary OS 0.4
VIM 7.4

My generated.vim content: https://gist.github.com/beeblebrox3/7d4a0886633eefbb41fd4cde812f21c4
I have the same problem on Mint 18, also on a fresh install.

**Comment by cassiobotaro** [comment]
@beeblebrox3 
Verify that you have already installed all dependencies: `sudo apt-get install git exuberant-ctags ncurses-term curl` 
Linux tip: use vim-nox instead of vim: `sudo apt-get install vim-nox`
After copy `.vimrc` into `$HOME` run the follow command `vim +PlugInstall +qall`

**Comment by beeblebrox3** [comment]
Oh, I didn't know about this dependencies. But no success :(
Thanks, @cassiobotaro

**Comment by cassiobotaro** [comment]
@beeblebrox3 delete ` ~/.vim` directory, install dependencies and try again. If error persists let's schedule a call...

**Comment by beeblebrox3** [comment]
Didn't work, but I did something that worked.
I downloaded the vim-plug with
`curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`

And run vim, but got the error "Cannot find color scheme 'molokai'", like on issue #107. But vim opened. Then I run `:PlugInstall` and looks like is working now. I will try on my work computer (the one with mint) to see if works there too.

Thanks, @cassiobotaro .

**Comment by fbidu** [comment]
I just had this same issue. I tried to install my bootstrapped `vimrc` without installing the dependencies and got the same error log in the beggining of the issue. I installed the dependencies, deleted my `.vim` folder but still got the same behavior.

After that, I installed the  `vim-plug` using the command suggested by @beeblebrox3, got the same error regarding `molokai` but everything worked fine

**Comment by moseshu** [comment]
I run command :   vim +PluginInstall +qall,
note:my mac system os MacOS Mojave

an error happened 
Error detected while processing /Users/xp/.vimrc:
E117: Unknown function: vundle#begin
E492: Not an editor command: Plugin 'VundleVim/Vundle.vim'
E492: Not an editor command: Plugin 'scrooloose/nerdcommenter'
