### ISSUE TITLE
If possible use of a function keep cursor and search registers during call functions

### ISSUE THREAD

**Issue by voyeg3r** [avelino/vim-bootstrap#220]
Hey guys, I know there are some plugins to clean extra spaces without moving cursor point, but there are other advantages of using something like this: 
I found an awesome vim function calle "Preserve" on this blog post:
https://technotales.wordpress.com/2010/03/31/preserve-a-vim-function-that-keeps-your-state/

"The thing is: The function "Preserve can be calle by other functions 
" I think is a good thing to do when it comes to vim improvement

**Comment by cassiobotaro** [comment]
Useful, but not something that should be standard on vim-bootstrap.
