### ISSUE TITLE
How can I check scripts written for different versions of Python

### ISSUE THREAD

**Issue by ning05130513** [avelino/vim-bootstrap#223]
Currently I found the syntax checking is for python2, but I want for python3. Thanks in advance.

**Comment by ning05130513** [comment]
I solve it by replacing
`let g:syntastic_python_checkers=['python', 'flake8']`
to
`let g:syntastic_python_checkers=['python3', 'flake8']`
in my .vimrc file.

**Comment by avelino** [comment]
Recommend used file `~/.vimrc.local` you personal config

**Comment by cassiobotaro** [comment]
@ning05130513 When you use virtualenv with flake8 installed inside that, it will be recognized automatically.
