### ISSUE TITLE
Syntax highlighting for print() in Python3

### ISSUE THREAD

**Issue by ning05130513** [avelino/vim-bootstrap#224]
In PEP8, I found the following rule:
> Immediately before the open parenthesis that starts the argument list of a function call:
> 
> Yes: spam(1)
> No:  spam (1)

my vim doesn't coloring the keyword 'print' when typing
`print("something")`
but it does for
`print ("something")`

how could I fix my .vimrc to get the result I want?

**Comment by cassiobotaro** [comment]
It's related to [vim-polyglot](https://github.com/sheerun/vim-polyglot). You can disable polyglot for python ` let g:polyglot_disabled = ['python']`.

**Comment by cassiobotaro** [comment]
03a03d23e1921e1527e12e36637144d7d26cebc3
We returns with polyglot but with python deactivate by default.
I also open a issue to fix that: https://github.com/mitsuhiko/vim-python-combined/issues/5, maybe soon I send a PR too.
