### ISSUE TITLE
vim-polyglot is not updated

### ISSUE THREAD

**Issue by cassiobotaro** [avelino/vim-bootstrap#229]
Why not change vim-polyglot to especific syntax and etc by language?
I run the build script and many packages are outdated.
We can run these plugins only on specifics filetypes for example:
`Plug 'hdima/python-syntax', {'for': 'python'}`

@avelino @lerrua, what do you think?

**Comment by lerrua** [comment]
We had some bugs after merge this PR for example the issue #231 by missing vim-polyglot, without it we'll missing support for nginx, less, puppet and others file types.

**Comment by cassiobotaro** [comment]
As discussed with you personally, i have another solution to make everboady happy, i will submit a PR asap.

**Comment by cassiobotaro** [comment]
@lerrua it's Alive! 03a03d23e1921e1527e12e36637144d7d26cebc3 Vim-polyglot is now updated! 
We've still with problems with print, but the simplest solution is deactivate polyglot on this case or similar.

**Comment by lerrua** [comment]
great! 🍺
