### ISSUE TITLE
vim highlight color not correct(comments in code)

### ISSUE THREAD

**Issue by rupertqin** [avelino/vim-bootstrap#231]
<img width="690" alt="screen shot 2016-12-21 at 2 14 06 pm" src="https://cloud.githubusercontent.com/assets/729242/21381381/ef6e971a-c795-11e6-9dc7-5a5c56a7e1b0.png">

then I comment two lines in .vimrc, the hightlight color look well as Macvim:
```vimrc
let g:CSApprox_loaded = 1
let g:indentLine_faster = 1
```

**Comment by cassiobotaro** [comment]
03a03d23e1921e1527e12e36637144d7d26cebc3 will fix this problem.

**Comment by lerrua** [comment]
@rupertqin try to generate a new vimrc file please.

**Comment by rupertqin** [comment]
@lerrua I just generate .vimrc from https://vim-bootstrap.com/,   the problem is still exsit.

**Comment by avelino** [comment]
deploy now, sorry delay.

**Comment by cassiobotaro** [comment]
@rupertqin try to generate a new vimrc file please

**Comment by rupertqin** [comment]
@cassiobotaro not work.

**Comment by cassiobotaro** [comment]
@rupertqin plase specify your vim version and OS. We have to reproduce this error...

**Comment by rupertqin** [comment]
@cassiobotaro Vim 8.0 in MacOS X

**Comment by cassiobotaro** [comment]
@rupertqin  Which languages you selected? After generate new .vimrc, do you run PlugInstall again?

**Comment by cassiobotaro** [comment]
@rupertqin any news?

**Comment by rupertqin** [comment]
@cassiobotaro It's nice now when I reinstalled it!
