### ISSUE TITLE
Opening a man page in a split

### ISSUE THREAD

**Issue by mhammerc** [avelino/vim-bootstrap#233]
Hello :)

Vim-bootstrap is by far my favorite configuration :)
I'm developing in C all the time, and a missing an important feature to me is the simple fact to open a man page.
I know MAJ+k to open the man page of the underlying function name but it would be better if we can open the man page in another split.
I'm thinking to this plugin https://github.com/ludwig/split-manpage.vim. I think many others exist. What do you think?
If you think it's a good idea but you are bored, I can submit a PR.

Thank you!

**Comment by cassiobotaro** [comment]
@mhammerc I think split-manpage is more useful for C programmers, then I added this package when C is  one of the selected languages. Do you agree? Fow while, you can generate new .vimrc locally but asap, it will possible by the website. @avelino, please do a deploy.

**Comment by mhammerc** [comment]
Yes, I'm working in C, I do agree. Thank you a lot!
