### ISSUE TITLE
no syntax highlighting

### ISSUE THREAD

**Issue by amigo421** [avelino/vim-bootstrap#236]
created init.vim with support for C, PHP, Python, 
just only added manually the line:

`Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
`

syntax on - does exist there,
![image](https://cloud.githubusercontent.com/assets/3259933/21751745/3f6332ee-d5dd-11e6-920e-41b50cd04481.png)

but no highlighting for c,h files:
![image](https://cloud.githubusercontent.com/assets/3259933/21751793/191f2088-d5de-11e6-99b1-d3f714526305.png)

see the init.vim in attachment
[init.txt](https://github.com/avelino/vim-bootstrap/files/692296/init.txt)

**Comment by amigo421** [comment]
commented out colour schema solved the prolem

**Comment by cassiobotaro** [comment]
![image](https://cloud.githubusercontent.com/assets/3127847/21753608/b604f668-d5d7-11e6-8753-71cfcc7a4d24.png)

**Comment by amigo421** [comment]
reduce a generating to C types only ,and didn't add YCM autocompletion (by the way, C version doesn't contain anyone similar plugin? I mean autocompletion based on clang?)
so the same issue - no syntax highlighting. I didn't face with a work in text-mode terminal, so can the problem be related with a using this in SSH session?

**Comment by cassiobotaro** [comment]
When you select c, these plugins are added to your .vimrc(or init.vim):
    [manpage](https://github.com/ludwig/split-manpage.vim)
    [c.vim](https://github.com/vim-scripts/c.vim)
None of boths provides autocompletion based on clang. Use .vimrc.local.bundles to install custom packages.
We already tried to add youcompleteme as vim-bootstrap package but it's complex to integrate(many dependencies). If you found some interesting c package with this feature, submit a PR.

About the highlight, yes, can be a ssh issue, we have to check. give us more details to how to reproduce the bug.

**Comment by cassiobotaro** [comment]
@amigo421 I will close this issue, but feel free to reopen if the problem persists. I think the problem with highlight is related to how you run vim inside a ssh session. If you want to talk more about that, we have a [chat](https://gitter.im/avelino/vim-bootstrap)
