### ISSUE TITLE
difference between the result from cli and web site 

### ISSUE THREAD

**Issue by amigo421** [avelino/vim-bootstrap#237]
when I'm doing the same target (neovim and default langs) via web
`let vimplug_exists=expand('~/.config/nvim/autoload/plug.vim')
` 
but via cli this line looks like:
`let vimplug_exists=expand('~/.neovim/autoload/plug.vim')
`
seems first case is more accurate, no?

**Comment by cassiobotaro** [comment]
@avelino Please do a deploy and close this issue.

**Comment by cassiobotaro** [comment]
It's related to this commit: https://github.com/avelino/vim-bootstrap/commit/a86698bc2241e6f0510031391d077d705c6f1609

**Comment by cassiobotaro** [comment]
I'm closing this issue @amigo421 because is a invalid issue, try to pull the last version and build again. If the problems persists, feel free to reopen this issue.
