### ISSUE TITLE
CTRL-I is not Working.

### ISSUE THREAD

**Issue by SachinSetiya** [avelino/vim-bootstrap#239]
Hello Everyone!

I tried using CTRL+I but it is not working, However CTRL+O is working fine.
I use neovim.

**Comment by cassiobotaro** [comment]
The same bug here in vim, I'm inspecting.

**Comment by SachinSetiya** [comment]
I also tried with vim , found the same bug.

**Comment by cassiobotaro** [comment]
<C-i> and <Tab> are strictly equivalent and we are overriding it.

nnoremap <Tab> gt 

`:verbose map <c-i>` reveals the problem.

**Comment by SachinSetiya** [comment]
Thanks cassiobotaro!

For the time I have removed this line , just to get it work 

nnoremap <Tab> gT

**Comment by cassiobotaro** [comment]
@SachinSetiya add `nummap <C-i>`to your .vimrc.local and problem solved :smile:
