### ISSUE TITLE
SmartIndent in python is harmful

### ISSUE THREAD

**Issue by laarmen** [avelino/vim-bootstrap#241]
Hi,

The Python configuration explicitly sets smartindent. However, this introduces the following behavior for comment lines, at least in version 7.4.1689 (on Ubuntu 16.04 LTS)

> 	When typing '#' as the first character in a new line, the indent for
> 	that line is removed, the '#' is put in the first column.  The indent
> 	is restored for the next line.  If you don't want this, use this
> 	mapping: ":inoremap # X^H#", where ^H is entered with CTRL-V CTRL-H.
> 	When using the ">>" command, lines starting with '#' are not shifted
> 	right.

This behavior is clearly not practical when commenting Python code!

**Comment by cassiobotaro** [comment]
I will investigate how to improve this behaviour, thanks to report @laarmen.

**Comment by cassiobotaro** [comment]
Fixed with 0cc1b90dd98a7130a2118e88e860c226dbbd33db

**Comment by cassiobotaro** [comment]
More about this bug: http://stackoverflow.com/questions/2360249/vim-automatically-removes-indentation-on-python-comments

**Comment by laarmen** [comment]
Thanks for the fix, and generally for the service, it saves me tons of time when hopping from machine to machine.
