### ISSUE TITLE
Opinion about use FZF instead of CtrlP

### ISSUE THREAD

**Issue by lerrua** [avelino/vim-bootstrap#244]
Guys,

I've use FZF since last week with some [CtrlP and Grep shortcuts](https://github.com/lerrua/Dotfiles/blob/master/vimrc.local#L134) in my vimrc local.
My opinion is that FZF is amazing, works great on terminal and have an incredible speed (i'm using with AG command). 
Anyway, what you guys think about FZF? It'll be good to put this as default for vim-bootstrap?

**Comment by cassiobotaro** [comment]
If  we are able to reproduce the same behaviour of ctrlp and grep, without add ag as dependency, I'm favorable to fzf become the default.
