### ISSUE TITLE
Rust Language

### ISSUE THREAD

**Issue by SirDoctors** [avelino/vim-bootstrap#245]
It would be awesome if these plugins would be an option for rust lang plugins.

The offical plugin for rust is [rust.vim](https://github.com/rust-lang/rust.vim) with completion with [vim-racer](https://github.com/racer-rust/vim-racer) or the in development [language client](https://github.com/autozimu/LanguageClient-neovim) (relies on racer making vim-racer redundent if the lang server is installed)

Additionally https://areweideyet.com/#vim is worth a look.

**Comment by cassiobotaro** [comment]
Deploy the new version asap. 
![image](https://cloud.githubusercontent.com/assets/3127847/24315262/d6a0df18-10c4-11e7-8d70-9bd7d8308035.png)
