### ISSUE TITLE
:GoRun doesn't find file

### ISSUE THREAD

**Issue by citizenrich** [avelino/vim-bootstrap#247]
Heyo. I see an error on a clean bootstrap-vim .vimrc when running a simple 'hello, world' go program. Invoked per vim-go with :GoRun

go run: no go files listed

Using homebrew vim on mac, no alterations to .vimrc.
vim: stable 8.0.0503 (bottled), HEAD
compiled with: --with-lua --with-python3

**Comment by cassiobotaro** [comment]
What's your os and go version ? Do you set $GOPATH ?

**Comment by citizenrich** [comment]
Hi. Yes, 'echo $GOPATH' is giving the correct path. go version is 1.8. :GoPath in vim also shows the correct path.

**Comment by citizenrich** [comment]
Other vim-go stuff works. :GoInstall installs as expected, linters work, etc. Just GoRun fails. Here's the usual hello, world.

package main

import "fmt"

func main() {
	fmt.Println("vim-go")
}

**Comment by cassiobotaro** [comment]
@avelino @lerrua One of you can confirm this problem?

**Comment by citizenrich** [comment]
Could be related to https://github.com/fatih/vim-go/issues/1208 or https://github.com/fatih/vim-go/issues/1243

**Comment by citizenrich** [comment]
Yeah, more I look at this it seems to be an issue with vim-go. I'll close this and keep an eye out on vim-go and add a comment here if it's resolved there.

**Comment by citizenrich** [comment]
This was fixed in https://github.com/fatih/vim-go/issues/1243
