### ISSUE TITLE
Display vim-bootstrap version inside vimrc

### ISSUE THREAD

**Issue by lerrua** [avelino/vim-bootstrap#249]
Hello guys,

What do you think about add the current version inside on generate vimrc file? For example:

```
" vim-bootstrap v728123 (commit hash)
```

It'll be better to help some users when find and to report a bug.

**Comment by cassiobotaro** [comment]
I'm implementing this, will delivered asap.

**Comment by cassiobotaro** [comment]
@lerrua 
![captura de tela de 2017-04-23 01-28-28](https://cloud.githubusercontent.com/assets/3127847/25310814/52234eda-27c4-11e7-8d06-9bc2203ab7af.png)
![captura de tela de 2017-04-23 01-27-21](https://cloud.githubusercontent.com/assets/3127847/25310816/592b85b2-27c4-11e7-9068-5da9903bb17a.png)

**Comment by lerrua** [comment]
good 🍺
