### ISSUE TITLE
vim-mypy should also be added to vimrc file for python.

### ISSUE THREAD

**Issue by RatanShreshtha** [avelino/vim-bootstrap#265]
[Mypy](https://github.com/python/mypy) is an optional static type checker for Python. You can add type hints to your Python programs using the standard for type annotations introduced in Python 3.5 (PEP 484), and use mypy to type check them statically.

And vim-mypy is a Vim plugin for executing Python's optional static type checker MyPy.

I think that vim-mypy should also be added to vimrc file for python when generated through vim-bootstrap.

**Comment by cassiobotaro** [comment]
We're using syntastic as analyzer and it have support for mypy, only add `let g:syntastic_python_checkers = ['mypy', 'flake8', 'python']` in `.vimrc.local`.

When mypy project becomes more stable, we can includde it as default.

**Comment by RatanShreshtha** [comment]
thanks
