### ISSUE TITLE
Create opensuse package vim-bootstrap

### ISSUE THREAD

**Issue by chocoelho** [avelino/vim-bootstrap#275]
Way of using:

```
zypper in vim-bootstrap
vim-bootstrap -langs=python,lua,ruby,javascript,haskell -editor=vim > ~/.vimrc
```

Today install https://github.com/avelino/vim-bootstrap#offline-usage

**Comment by chocoelho** [comment]
I was able to generate some sample RPM for some SUSE/OpenSUSE distributions at https://build.opensuse.org/package/show/home:chocoelho/vim-bootstrap. One thing that was found after installing the generated RPM was that it depended on the path for the template. Another issue will be created to handle this.

**Comment by chocoelho** [comment]
Also, it'll be good to have some release system. It'll be better to track changes. Meanwhile, tars are being generated based on the commit hash, .e.g: `vim-bootstrap-1.0+git9c1c51e.tar.gz` generates `vim-bootstrap-1.0-git9c1c51e.rpm`.

**Comment by chocoelho** [comment]
I was able to generate a working RPM for OpenSUSE thanks to @cassiobotaro and submitted `vim-bootstrap` from my personal repo to OpenSUSE's official `devel:tools` repo. You can follow the progress at: https://build.opensuse.org/request/show/541015

**Comment by chocoelho** [comment]
`vim-bootstrap` is already available in the official repository on openSUSE Tumbleweed, and in official `devel:tools` for Leap 42.x versions. It'll soon be submitted to review for the future Leap 15 release.

**Comment by chocoelho** [comment]
https://software.opensuse.org/package/vim-bootstrap

**Comment by cassiobotaro** [comment]
Thanks @chocoelho !

**Comment by avelino** [comment]
update install topic on readme
