### ISSUE TITLE
Consider replacing Syntastic with Ale

### ISSUE THREAD

**Issue by henrebotha** [avelino/vim-bootstrap#278]
Vim Bootstrap currently uses Syntastic for linting. However, as of Vim 8, there is support for async plugins. The plugin [Ale](https://github.com/w0rp/ale) does the same job as Syntastic, but does so asynchronously. This means that the user can get feedback as they type, without pauses for the linter to process. The impact of this cannot be overstated; a plugin that does its work slowly and only on demand is a plugin that soon ceases to be used.

Migrating from Syntastic to Ale is pretty frictionless from my experience.

Thoughts?

**Comment by cassiobotaro** [comment]
Unfortunately ubuntu LTS still remains in version 7. We already consider this change, it's a question of time.

**Comment by henrebotha** [comment]
Is it not something that could be installed conditionally? It seems like Vim Bootstrap already checks the Vim version for some other features.
