### ISSUE TITLE
Python virtualenv +  ctags

### ISSUE THREAD

**Issue by sidneijp** [avelino/vim-bootstrap#288]
- Vim bootstrap version(number in first line): 5268b45
- Operating system: 4.10.0-40-generic 44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Vim/Nvim version: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
- Languages: python

## Description

I'm have trouble using *Go to the Class/Method definition* (`,c`) when the reference is in a package installed on the active virtualenv. Does it should work with virtualenv? If it's possible, what can I do to achieve it?

**Comment by cassiobotaro** [comment]
Thanks to report, i'll take a look.

**Comment by cassiobotaro** [comment]
`,c` closes buffer, use `<leader>g` or `<leader>d` to go to assignments or definition. `<leader>` is mapping to , on vim-bootstrap.
