### ISSUE TITLE
Indent guides cannot be replaced

### ISSUE THREAD

**Issue by VentGrey** [avelino/vim-bootstrap#294]
- Vim bootstrap version(number in first line): b990cad
- Operating system: Debian 9.3 Gnu/Linux
- Vim/Nvim version:8.0
- Languages: C, Python, HTML5, JS, PHP

## Description
**Issue happens on GVIM**
I think title is self-explainatory, when I replace the indentline plugin char for one of my desire it gets overriden or overwritten, I tried using a minimal vimrc file to see if the plugin was buggy but It worked, I have these lines on the generate.vim I renamed and placed as .vimrc

![seleccion_005](https://user-images.githubusercontent.com/24773698/39409342-12b7a3ca-4bab-11e8-9a22-62a847d0692b.png)

however even after saving, quitting and editing with another text editor such as gedit, pluma or even emacs indent lines are not replaced

![seleccion_006](https://user-images.githubusercontent.com/24773698/39409351-2d1fd822-4bab-11e8-8f7a-63f7097ac6fa.png)

**Comment by cassiobotaro** [comment]
Put your personal configurations on `.vimrc.local` or equivalent on neovim. I tested here on vim and neovim, and both works well.

![image](https://user-images.githubusercontent.com/3127847/54648474-272ee000-4a85-11e9-8911-6e9a93f58212.png)
