### ISSUE TITLE
Copy command with linux OS

### ISSUE THREAD

**Issue by andys8** [avelino/vim-bootstrap#295]
I was trying to use `CTRL + C` to copy text to the clipboard. There is this part of the configuration:

```
if has('macunix')
  " pbcopy for OSX copy/paste
  vmap <C-x> :!pbcopy<CR>
  vmap <C-c> :w !pbcopy<CR><CR>
endif
```

I though `has('macunix')` could be "Mac or Linux", but it isn't. So it wasn't working even though I have `pbcopy` available. This was done on purpose: https://github.com/avelino/vim-bootstrap/issues/43

Are there other options which would work under more systems? Or can there be different branches?

**Comment by zx1986** [comment]
How could I disable vim delete buffer into Mac clipboard ???

**Comment by cassiobotaro** [comment]
Ctrl-c only works on Mac. `y` copy to clipboard on linux if you have `+clipboard` when execute `vim --verision`. Many distributions you should install gvim to allow copy to clipboard. 

@zx1986 vim delete buffer?

**Comment by cassiobotaro** [comment]
@andys8 if you have more questions, feeel free to reopen issue or open a new one. Sorry for the late reply.

**Comment by andys8** [comment]
That's it. `+clipboard` is often not the default. Thanks for your answer.
https://stackoverflow.com/questions/3961859/how-to-copy-to-clipboard-in-vim#comment36299939_3961859
