### ISSUE TITLE
Disable vim delete/copy buffer into Mac's clipboard

### ISSUE THREAD

**Issue by zx1986** [avelino/vim-bootstrap#300]
- Vim bootstrap version(number in first line): latest
- Operating system: macOS latest
- Vim/Nvim version: Nvim 
- Languages: Any programming languages

## Description

Every I delete (dd) or yank (yy) things in vim, it will overwrite my OS clipboard,

1. Sometimes, I just copy something out of vim,
2. And I wanna paste my things into vim,
3. But, first I will delete (dd / dw) things in vim,
4. Then! vim overwrite my clipboard with the things I just delete!

I really hate this.
How could I disable this behavior?

I found config:

```
"" Copy/Paste/Cut
if has('unnamedplus')
  set clipboard=unnamed,unnamedplus     # I comment out this and it works.
endif

noremap YY "+y<CR>                     # I wanna keep this
noremap <leader>p "+gP<CR>     # I wanna keep this
noremap XX "+x<CR>                    # I wanna keep this

if has('macunix')
  " pbcopy for OSX copy/paste
  vmap <C-x> :!pbcopy<CR>
  vmap <C-c> :w !pbcopy<CR><CR>
endif
``` 

Any other better solution?

**Comment by zx1986** [comment]
refs #71

**Comment by shirohana** [comment]
## Just disable clipboard flags that your found

Both commented down this line:

```vimrc
" set clipboard=unnamed,unnamedplus # I comment out this and it works.
```

or set to `none` as your customization like:

```vimrc
set clipboard=
```

would works for you.

Is there any reason caused you don't do this way?

## Reference

These docs copied from built-in manual:

```
						*clipboard-unnamed*
	unnamed		When included, Vim will use the clipboard register '*'
			for all yank, delete, change and put operations which
			would normally go to the unnamed register.  When a
			register is explicitly specified, it will always be
			used regardless of whether "unnamed" is in 'clipboard'
			or not.  The clipboard register can always be
			explicitly accessed using the "* notation.  Also see
			|clipboard|.

						*clipboard-unnamedplus*
	unnamedplus	A variant of the "unnamed" flag which uses the
			clipboard register '+' (|quoteplus|) instead of
			register '*' for all yank, delete, change and put
			operations which would normally go to the unnamed
			register.  When "unnamed" is also included to the
			option, yank and delete operations (but not put)
			will additionally copy the text into register
			'*'. See |clipboard|.
```

**Comment by shirohana** [comment]
Btw, you can use

```
:set clipboard<CR>
```
or
```
:set clipboard?<CR>
```
to preview current flags of `clipboard`, and tell us what it shows.

**Comment by zx1986** [comment]
@shirohana I don't wanna rewrite the vim-bootstrap's default config.
But I think I found the property way:
I overwrite clipboard in the `vimrc.local` which my custom config.
