### ISSUE TITLE
FZF history shortcut in conflict with 'redo'

### ISSUE THREAD

**Issue by Shourai** [avelino/vim-bootstrap#308]
Pull request #298, which adds CTRL-R as a mapping for FZF history conflicts with redo.
Not sure which different mapping would work better, but activating :History in command mode
also does not work as that is for pasting from register.

**Comment by Shourai** [comment]
Mapping it to `CTRL-h` does not solve it as it is already mapped to `CTRL-w h`.
A suggestion would be assigning it to leader-y as that is not used.

**Comment by cassiobotaro** [comment]
thanks @Shourai , I update to `<leader>y`
