### ISSUE TITLE
Add default support for vue.js and TypeScript

### ISSUE THREAD

**Issue by guledali** [avelino/vim-bootstrap#314]
I know that vim-bootstrap has some default config for supporting `jsx`, can similar be done for `.vue` file format. The other thing is native support for TypeScript

**Comment by cassiobotaro** [comment]
Do you have any suggestions for plugins?

**Comment by guledali** [comment]
For `vue.js` this seems to be really popular https://github.com/posva/vim-vue

For TypeScript I have no idea

**Comment by guledali** [comment]
But yeah I'm glad that you responded so quickly

**Comment by cassiobotaro** [comment]
Thanks @guledali, I will submit a PR to include these packages as soon as possible.

**Comment by cassiobotaro** [comment]
- [x] Typescript support (5791188591744ad6383b8ae0c164134a57abcd08)
- [ ] VueJS support(#315) _in progress_

About autocomplete, we have to test ALE completions. For while you should add in your `.vimrc.local` or `local_init.vim`  
```viml
" ale
let g:ale_completion_enabled = 1
```

**Comment by guledali** [comment]
Thanks, you guys are the real heroes!!

**Comment by cassiobotaro** [comment]
#315 was merged, I think we can close this issue. Thanks @guledali !
