### ISSUE TITLE
Useless configuration

### ISSUE THREAD

**Issue by rhysd** [avelino/vim-bootstrap#41]
Below configuration is already in `vimrc_example.vim` bundled in Vim and it is loaded before `.vimrc`.

```vim
"" Remember cursor position
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
```

**Comment by cassiobotaro** [comment]
I think its already changed. Reopen if necessary.
