### ISSUE TITLE
Error when generate vimrc to [js, ruby, html]

### ISSUE THREAD

**Issue by adimircolen** [avelino/vim-bootstrap#52]
![screen shot 2014-09-01 at 12 24 32 pm](https://cloud.githubusercontent.com/assets/220818/4109971/2aa78a9a-31ec-11e4-875c-0e6169d4622a.png)

**Comment by lerrua** [comment]
this error only occurs using macvim?

**Comment by EvanMarkHopkins** [comment]
in my case it was Debian, but I haven't played with it in quite some time... I'd rather not revisit this. :tired_face:

**Comment by adimircolen** [comment]
You can run 
```
:NeoBundle
```

**Comment by cassiobotaro** [comment]
@adimircolen We deployed a new version, can you test if bug persists?

**Comment by adimircolen** [comment]
@cassiobotaro No, i can't test this. I change my configs to solve this.

**Comment by lerrua** [comment]
after this new release i guess it's working.

**Comment by cassiobotaro** [comment]
@ghost And you?

**Comment by lerrua** [comment]
We are using Vim-Plug now.
