### ISSUE TITLE
Enhanched '%' behavior (e.g. for html)

### ISSUE THREAD

**Issue by tvannahl** [avelino/vim-bootstrap#84]
Would recommend the following plugin to enhance the '%' command behavior. This is very helpfull
in HTML documents, so you can jump to the corresponding tag with '%'.

``` vim
BundleInstall 'vim-scripts/matchit.zip'
```

**Comment by cassiobotaro** [comment]
Since vim 6.0, matchit.vim has been included in the standard vim distribution.

http://www.vim.org/scripts/script.php?script_id=39
