### ISSUE TITLE
fugitive problems

### ISSUE THREAD

**Issue by m-weigand** [avelino/vim-bootstrap#89]
After creating the vimrc file for python and standard vim, I'm promted with the question to install bundles now:

```
Not installed bundles:  ['vimproc.vim', 'gre...', 'vim-airline', 'indentLine', 'vim-polyglot']
Install bundles now?
(y)es, [N]o:
```
Selecting "yes" will yield errors regarding the some fugitive functions:

```
Zeile   23:
E117: Unbekannte Funktion: fugitive#statusline
```

Cloning the fugitive package by hand and restarting parting successfully installs the packages.

```
cd .vim/bundle/neobundle.vim/plugin/
git clone https://github.com/tpope/vim-fugitive.git
```

This error occurred on two Debian Wheezy machines with the vim version "VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 10 2013 02:28:47)".

**Comment by lerrua** [comment]
@m-weigand on installation try to run vim +BundleInstall! +BundleClean +qall from your command line.
I believe this error is because it doesn't find the `statusline` function in first install.
