### ISSUE TITLE
Some extensions for CtrlP plugin

### ISSUE THREAD

**Issue by lerrua** [avelino/vim-bootstrap#92]
Hi guys!

I've found some plugins for improve the CtrlP plugin.

https://github.com/tacahiroy/ctrlp-funky 
https://github.com/FelikZ/ctrlp-py-matcher

Maybe the ctrlp-py-matcher be a promising plugin.

**Comment by pedroandrade** [comment]
:+1: 
this sounds great
I'm using ctrlp-py-matcher, it's a awesome plugin.

**Comment by ivancrneto** [comment]
I am also using with ctrlp-py-matcher, it really improves the matching speed by a lot.
If you have the silver searcher it improves even more (https://github.com/ggreer/the_silver_searcher)

:+1:

**Comment by lerrua** [comment]
ctrlp-py-matcher only works on vim > 7.4, its a problem.

**Comment by ivancrneto** [comment]
can we have a condition checking for the version?

**Comment by ivancrneto** [comment]
maybe https://github.com/JazzCore/ctrlp-cmatcher/

**Comment by lerrua** [comment]
@ivancrneto ctrlp-cmatcher has some C dependencies, vim-bootstrap must be easy to install... Maybe the condition checking for the version be an better idea.

**Comment by ivancrneto** [comment]
:+1:
