### ISSUE TITLE
Removed .vimrc.local.bundles of .vimrc

### ISSUE THREAD

**Issue by coisa** [avelino/vim-bootstrap#97]
The source ~/.vimrc.local.bundles was removed from .vimrc, why?

**Comment by avelino** [comment]
@coisa not removed[1]
https://github.com/avelino/vim-bootstrap/blob/master/vim_template/vimrc#L380

**Comment by coisa** [comment]
.vimrc.local still there, but .vimrc.local.bundles are not!
Em 05/02/2015 12:32, "Thiago Avelino" <notifications@github.com> escreveu:

**Comment by coisa** [comment]
https://github.com/avelino/vim-bootstrap/commit/663727403280888cd3511df34a5d29795a64a28f

**Comment by avelino** [comment]
@coisa thanks man!
Fixed...
